# Change these first
owner: ytkg # Your GitHub username
repo: status.takagi.blog # Your GitHub repository name

# Add your sites here
sites:
  - name: Blog
    url: https://takagi.blog/
  - name: Note
    url: https://note.takagi.blog/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.takagi.blog
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.takagi.blog
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
